create table if not exists public.catalog_sync_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('completed', 'failed')),
  started_at timestamptz not null,
  finished_at timestamptz not null,
  duration_ms integer not null default 0,
  total_collected_count integer not null default 0,
  total_imported_count integer not null default 0,
  total_updated_count integer not null default 0,
  total_skipped_count integer not null default 0,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_catalog_sync_runs_started_at
on public.catalog_sync_runs(started_at desc);

alter table public.catalog_sync_runs enable row level security;

revoke all on public.catalog_sync_runs from anon, authenticated;
